create table purchase_transactions (
    id bigint generated by default as identity primary key,
    description varchar(50) not null,
    transaction_date date not null,
    usd_amount numeric(19,2) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint chk_purchase_transactions_usd_amount_positive check (usd_amount > 0)
);